version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: healthcare-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: healthcare_db
    volumes:
      - mongodb_data:/data/db
    networks:
      - healthcare-network

  # Healthcare Backend API
  backend:
    build: .
    container_name: healthcare-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/healthcare_db
      JWT_SECRET: xaki1253ya
      JWT_EXPIRES_IN: 7d
      PORT: 3000
      NODE_ENV: production
      MAX_FILE_SIZE: 10485760
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - mongodb
    networks:
      - healthcare-network

  # MongoDB Express (Database Admin UI)
  mongo-express:
    image: mongo-express:1.0.0
    container_name: healthcare-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongodb
    networks:
      - healthcare-network

volumes:
  mongodb_data:

networks:
  healthcare-network:
    driver: bridge
